# Generated by Django 5.2.7 on 2025-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post/cute.jpeg', upload_to='media'),
        ),
    ]
